spring.data:
  cassandra:
    contactPoints: localhost
    port: 9042
    keyspaceName: employ
    keyspaceReplicationFactor: 3
    consistency-level: quorum
    sslEnabled: false
    clientTruststore: ~/client.truststore.file
    trustStorePassword: trustme
    slowQueryThreshold: 200