// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/location.proto

package io.employed.proto;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string streetAddress = 1;</code>
   */
  String getStreetAddress();
  /**
   * <code>string streetAddress = 1;</code>
   */
  com.google.protobuf.ByteString
      getStreetAddressBytes();

  /**
   * <code>string city = 2;</code>
   */
  String getCity();
  /**
   * <code>string city = 2;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string state = 3;</code>
   */
  String getState();
  /**
   * <code>string state = 3;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string country = 4;</code>
   */
  String getCountry();
  /**
   * <code>string country = 4;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string zip = 5;</code>
   */
  String getZip();
  /**
   * <code>string zip = 5;</code>
   */
  com.google.protobuf.ByteString
      getZipBytes();
}
