// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/company/company.proto

package io.employed.proto;

public interface CompanyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.Company)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string company_id = 1;</code>
   */
  String getCompanyId();
  /**
   * <code>string company_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCompanyIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string about = 3;</code>
   */
  String getAbout();
  /**
   * <code>string about = 3;</code>
   */
  com.google.protobuf.ByteString
      getAboutBytes();

  /**
   * <code>string avatar_url = 4;</code>
   */
  String getAvatarUrl();
  /**
   * <code>string avatar_url = 4;</code>
   */
  com.google.protobuf.ByteString
      getAvatarUrlBytes();

  /**
   * <code>string website = 5;</code>
   */
  String getWebsite();
  /**
   * <code>string website = 5;</code>
   */
  com.google.protobuf.ByteString
      getWebsiteBytes();

  /**
   * <code>.employed.io.Location headquarters = 6;</code>
   */
  boolean hasHeadquarters();
  /**
   * <code>.employed.io.Location headquarters = 6;</code>
   */
  io.employed.proto.Location getHeadquarters();
  /**
   * <code>.employed.io.Location headquarters = 6;</code>
   */
  io.employed.proto.LocationOrBuilder getHeadquartersOrBuilder();

  /**
   * <code>int32 founded_year = 7;</code>
   */
  int getFoundedYear();

  /**
   * <code>int32 size = 8;</code>
   */
  int getSize();
}
