// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/company/company.proto

package io.employed.proto;

public final class CompanyProto {
  private CompanyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_Company_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_Company_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036protocol/company/company.proto\022\013employ" +
      "ed.io\032\036protocol/common/location.proto\"\260\001" +
      "\n\007Company\022\022\n\ncompany_id\030\001 \001(\t\022\014\n\004name\030\002 " +
      "\001(\t\022\r\n\005about\030\003 \001(\t\022\022\n\navatar_url\030\004 \001(\t\022\017" +
      "\n\007website\030\005 \001(\t\022+\n\014headquarters\030\006 \001(\0132\025." +
      "employed.io.Location\022\024\n\014founded_year\030\007 \001" +
      "(\005\022\014\n\004size\030\010 \001(\005B#\n\021io.employed.protoB\014C" +
      "ompanyProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.employed.proto.LocationProto.getDescriptor(),
        }, assigner);
    internal_static_employed_io_Company_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employed_io_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_Company_descriptor,
        new String[] { "CompanyId", "Name", "About", "AvatarUrl", "Website", "Headquarters", "FoundedYear", "Size", });
    io.employed.proto.LocationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
