// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/user/user_request.proto

package io.employed.proto;

public interface CreateUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.CreateUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.employed.io.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.employed.io.Status status = 1;</code>
   */
  io.employed.proto.Status getStatus();

  /**
   * <code>.employed.io.User user = 2;</code>
   */
  boolean hasUser();
  /**
   * <code>.employed.io.User user = 2;</code>
   */
  io.employed.proto.User getUser();
  /**
   * <code>.employed.io.User user = 2;</code>
   */
  io.employed.proto.UserOrBuilder getUserOrBuilder();

  /**
   * <code>.employed.io.JobSeeker job_seeker = 3;</code>
   */
  boolean hasJobSeeker();
  /**
   * <code>.employed.io.JobSeeker job_seeker = 3;</code>
   */
  io.employed.proto.JobSeeker getJobSeeker();
  /**
   * <code>.employed.io.JobSeeker job_seeker = 3;</code>
   */
  io.employed.proto.JobSeekerOrBuilder getJobSeekerOrBuilder();

  /**
   * <code>.employed.io.Recruiter recruiter = 4;</code>
   */
  boolean hasRecruiter();
  /**
   * <code>.employed.io.Recruiter recruiter = 4;</code>
   */
  io.employed.proto.Recruiter getRecruiter();
  /**
   * <code>.employed.io.Recruiter recruiter = 4;</code>
   */
  io.employed.proto.RecruiterOrBuilder getRecruiterOrBuilder();

  public io.employed.proto.CreateUserResponse.UserTypeCase getUserTypeCase();
}
