// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/job/job_request.proto

package io.employed.proto;

public interface CreateJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.CreateJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.employed.io.Job job = 1;</code>
   */
  boolean hasJob();
  /**
   * <code>.employed.io.Job job = 1;</code>
   */
  io.employed.proto.Job getJob();
  /**
   * <code>.employed.io.Job job = 1;</code>
   */
  io.employed.proto.JobOrBuilder getJobOrBuilder();
}
