// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/match/match_request.proto

package io.employed.proto;

public interface CreateMatchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.CreateMatchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string match_user_id = 2;</code>
   */
  java.lang.String getMatchUserId();
  /**
   * <code>string match_user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getMatchUserIdBytes();
}
