// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/match/match_request.proto

package io.employed.proto;

/**
 * Protobuf type {@code employed.io.CreateMatchResponse}
 */
public  final class CreateMatchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employed.io.CreateMatchResponse)
    CreateMatchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateMatchResponse.newBuilder() to construct.
  private CreateMatchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateMatchResponse() {
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateMatchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            io.employed.proto.Match.Builder subBuilder = null;
            if (match_ != null) {
              subBuilder = match_.toBuilder();
            }
            match_ = input.readMessage(io.employed.proto.Match.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(match_);
              match_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.employed.proto.MatchRequestProto.internal_static_employed_io_CreateMatchResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.employed.proto.MatchRequestProto.internal_static_employed_io_CreateMatchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.employed.proto.CreateMatchResponse.class, io.employed.proto.CreateMatchResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.employed.io.Status status = 1;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.employed.io.Status status = 1;</code>
   */
  public io.employed.proto.Status getStatus() {
    io.employed.proto.Status result = io.employed.proto.Status.valueOf(status_);
    return result == null ? io.employed.proto.Status.UNRECOGNIZED : result;
  }

  public static final int MATCH_FIELD_NUMBER = 2;
  private io.employed.proto.Match match_;
  /**
   * <code>.employed.io.Match match = 2;</code>
   */
  public boolean hasMatch() {
    return match_ != null;
  }
  /**
   * <code>.employed.io.Match match = 2;</code>
   */
  public io.employed.proto.Match getMatch() {
    return match_ == null ? io.employed.proto.Match.getDefaultInstance() : match_;
  }
  /**
   * <code>.employed.io.Match match = 2;</code>
   */
  public io.employed.proto.MatchOrBuilder getMatchOrBuilder() {
    return getMatch();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != io.employed.proto.Status.FAILURE.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (match_ != null) {
      output.writeMessage(2, getMatch());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != io.employed.proto.Status.FAILURE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (match_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMatch());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.employed.proto.CreateMatchResponse)) {
      return super.equals(obj);
    }
    io.employed.proto.CreateMatchResponse other = (io.employed.proto.CreateMatchResponse) obj;

    boolean result = true;
    result = result && status_ == other.status_;
    result = result && (hasMatch() == other.hasMatch());
    if (hasMatch()) {
      result = result && getMatch()
          .equals(other.getMatch());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasMatch()) {
      hash = (37 * hash) + MATCH_FIELD_NUMBER;
      hash = (53 * hash) + getMatch().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.employed.proto.CreateMatchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.employed.proto.CreateMatchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.employed.proto.CreateMatchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.employed.proto.CreateMatchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.employed.proto.CreateMatchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employed.io.CreateMatchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employed.io.CreateMatchResponse)
      io.employed.proto.CreateMatchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.employed.proto.MatchRequestProto.internal_static_employed_io_CreateMatchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.employed.proto.MatchRequestProto.internal_static_employed_io_CreateMatchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.employed.proto.CreateMatchResponse.class, io.employed.proto.CreateMatchResponse.Builder.class);
    }

    // Construct using io.employed.proto.CreateMatchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      status_ = 0;

      if (matchBuilder_ == null) {
        match_ = null;
      } else {
        match_ = null;
        matchBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.employed.proto.MatchRequestProto.internal_static_employed_io_CreateMatchResponse_descriptor;
    }

    public io.employed.proto.CreateMatchResponse getDefaultInstanceForType() {
      return io.employed.proto.CreateMatchResponse.getDefaultInstance();
    }

    public io.employed.proto.CreateMatchResponse build() {
      io.employed.proto.CreateMatchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.employed.proto.CreateMatchResponse buildPartial() {
      io.employed.proto.CreateMatchResponse result = new io.employed.proto.CreateMatchResponse(this);
      result.status_ = status_;
      if (matchBuilder_ == null) {
        result.match_ = match_;
      } else {
        result.match_ = matchBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.employed.proto.CreateMatchResponse) {
        return mergeFrom((io.employed.proto.CreateMatchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.employed.proto.CreateMatchResponse other) {
      if (other == io.employed.proto.CreateMatchResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasMatch()) {
        mergeMatch(other.getMatch());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.employed.proto.CreateMatchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.employed.proto.CreateMatchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.employed.io.Status status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.employed.io.Status status = 1;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.employed.io.Status status = 1;</code>
     */
    public io.employed.proto.Status getStatus() {
      io.employed.proto.Status result = io.employed.proto.Status.valueOf(status_);
      return result == null ? io.employed.proto.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.employed.io.Status status = 1;</code>
     */
    public Builder setStatus(io.employed.proto.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.employed.io.Status status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private io.employed.proto.Match match_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.employed.proto.Match, io.employed.proto.Match.Builder, io.employed.proto.MatchOrBuilder> matchBuilder_;
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    public boolean hasMatch() {
      return matchBuilder_ != null || match_ != null;
    }
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    public io.employed.proto.Match getMatch() {
      if (matchBuilder_ == null) {
        return match_ == null ? io.employed.proto.Match.getDefaultInstance() : match_;
      } else {
        return matchBuilder_.getMessage();
      }
    }
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    public Builder setMatch(io.employed.proto.Match value) {
      if (matchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        match_ = value;
        onChanged();
      } else {
        matchBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    public Builder setMatch(
        io.employed.proto.Match.Builder builderForValue) {
      if (matchBuilder_ == null) {
        match_ = builderForValue.build();
        onChanged();
      } else {
        matchBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    public Builder mergeMatch(io.employed.proto.Match value) {
      if (matchBuilder_ == null) {
        if (match_ != null) {
          match_ =
            io.employed.proto.Match.newBuilder(match_).mergeFrom(value).buildPartial();
        } else {
          match_ = value;
        }
        onChanged();
      } else {
        matchBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    public Builder clearMatch() {
      if (matchBuilder_ == null) {
        match_ = null;
        onChanged();
      } else {
        match_ = null;
        matchBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    public io.employed.proto.Match.Builder getMatchBuilder() {
      
      onChanged();
      return getMatchFieldBuilder().getBuilder();
    }
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    public io.employed.proto.MatchOrBuilder getMatchOrBuilder() {
      if (matchBuilder_ != null) {
        return matchBuilder_.getMessageOrBuilder();
      } else {
        return match_ == null ?
            io.employed.proto.Match.getDefaultInstance() : match_;
      }
    }
    /**
     * <code>.employed.io.Match match = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.employed.proto.Match, io.employed.proto.Match.Builder, io.employed.proto.MatchOrBuilder> 
        getMatchFieldBuilder() {
      if (matchBuilder_ == null) {
        matchBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.employed.proto.Match, io.employed.proto.Match.Builder, io.employed.proto.MatchOrBuilder>(
                getMatch(),
                getParentForChildren(),
                isClean());
        match_ = null;
      }
      return matchBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employed.io.CreateMatchResponse)
  }

  // @@protoc_insertion_point(class_scope:employed.io.CreateMatchResponse)
  private static final io.employed.proto.CreateMatchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.employed.proto.CreateMatchResponse();
  }

  public static io.employed.proto.CreateMatchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateMatchResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateMatchResponse>() {
    public CreateMatchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateMatchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateMatchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateMatchResponse> getParserForType() {
    return PARSER;
  }

  public io.employed.proto.CreateMatchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

