// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/job.proto

package io.employed.proto;

public interface JobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.Job)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>.employed.io.Job.CatergoryType catergory = 2;</code>
   */
  int getCatergoryValue();
  /**
   * <code>.employed.io.Job.CatergoryType catergory = 2;</code>
   */
  Job.CatergoryType getCatergory();

  /**
   * <code>.employed.io.Job.Company company = 3;</code>
   */
  boolean hasCompany();
  /**
   * <code>.employed.io.Job.Company company = 3;</code>
   */
  Job.Company getCompany();
  /**
   * <code>.employed.io.Job.Company company = 3;</code>
   */
  Job.CompanyOrBuilder getCompanyOrBuilder();

  /**
   * <code>string description = 4;</code>
   */
  String getDescription();
  /**
   * <code>string description = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string shortDescription = 5;</code>
   */
  String getShortDescription();
  /**
   * <code>string shortDescription = 5;</code>
   */
  com.google.protobuf.ByteString
      getShortDescriptionBytes();

  /**
   * <code>double salary = 6;</code>
   */
  double getSalary();

  /**
   * <code>string avatarImage = 7;</code>
   */
  String getAvatarImage();
  /**
   * <code>string avatarImage = 7;</code>
   */
  com.google.protobuf.ByteString
      getAvatarImageBytes();

  /**
   * <code>.employed.io.Job.Tag tag = 8;</code>
   */
  boolean hasTag();
  /**
   * <code>.employed.io.Job.Tag tag = 8;</code>
   */
  Job.Tag getTag();
  /**
   * <code>.employed.io.Job.Tag tag = 8;</code>
   */
  Job.TagOrBuilder getTagOrBuilder();

  /**
   * <code>.employed.io.Job.JobAddress jobAddress = 9;</code>
   */
  boolean hasJobAddress();
  /**
   * <code>.employed.io.Job.JobAddress jobAddress = 9;</code>
   */
  Job.JobAddress getJobAddress();
  /**
   * <code>.employed.io.Job.JobAddress jobAddress = 9;</code>
   */
  Job.JobAddressOrBuilder getJobAddressOrBuilder();

  /**
   * <code>.employed.io.Job.Recruiter recruiter = 10;</code>
   */
  boolean hasRecruiter();
  /**
   * <code>.employed.io.Job.Recruiter recruiter = 10;</code>
   */
  Job.Recruiter getRecruiter();
  /**
   * <code>.employed.io.Job.Recruiter recruiter = 10;</code>
   */
  Job.RecruiterOrBuilder getRecruiterOrBuilder();

  /**
   * <code>string responsibilities = 11;</code>
   */
  String getResponsibilities();
  /**
   * <code>string responsibilities = 11;</code>
   */
  com.google.protobuf.ByteString
      getResponsibilitiesBytes();

  /**
   * <code>string requirements = 12;</code>
   */
  String getRequirements();
  /**
   * <code>string requirements = 12;</code>
   */
  com.google.protobuf.ByteString
      getRequirementsBytes();

  /**
   * <code>string experience = 13;</code>
   */
  String getExperience();
  /**
   * <code>string experience = 13;</code>
   */
  com.google.protobuf.ByteString
      getExperienceBytes();
}
