// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/job/job_request.proto

package io.employed.proto;

public final class JobRequestProto {
  private JobRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_CreateJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_CreateJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_CreateJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_CreateJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_JobsByTagsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_JobsByTagsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_JobsByTagsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_JobsByTagsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_JobsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_JobsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036protocol/job/job_request.proto\022\013employ" +
      "ed.io\032\034protocol/common/status.proto\032\026pro" +
      "tocol/job/job.proto\"1\n\020CreateJobRequest\022" +
      "\035\n\003job\030\001 \001(\0132\020.employed.io.Job\"W\n\021Create" +
      "JobResponse\022#\n\006status\030\001 \001(\0162\023.employed.i" +
      "o.Status\022\035\n\003job\030\002 \001(\0132\020.employed.io.Job\"" +
      "!\n\021JobsByTagsRequest\022\014\n\004tags\030\001 \003(\t\"4\n\022Jo" +
      "bsByTagsResponse\022\036\n\004jobs\030\001 \003(\0132\020.employe" +
      "d.io.Job\".\n\014JobsResponse\022\036\n\004jobs\030\001 \003(\0132\020" +
      ".employed.io.JobB&\n\021io.employed.protoB\017J",
      "obRequestProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.employed.proto.StatusProto.getDescriptor(),
          JobProto.getDescriptor(),
        }, assigner);
    internal_static_employed_io_CreateJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employed_io_CreateJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_CreateJobRequest_descriptor,
        new String[] { "Job", });
    internal_static_employed_io_CreateJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_employed_io_CreateJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_CreateJobResponse_descriptor,
        new String[] { "Status", "Job", });
    internal_static_employed_io_JobsByTagsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_employed_io_JobsByTagsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_JobsByTagsRequest_descriptor,
        new String[] { "Tags", });
    internal_static_employed_io_JobsByTagsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_employed_io_JobsByTagsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_JobsByTagsResponse_descriptor,
        new String[] { "Jobs", });
    internal_static_employed_io_JobsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_employed_io_JobsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_JobsResponse_descriptor,
        new String[] { "Jobs", });
    io.employed.proto.StatusProto.getDescriptor();
    JobProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
