// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/job-seeker/job_seeker.proto

package io.employed.proto;

public interface JobSeekerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.JobSeeker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string first_name = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phone_number = 5;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 5;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string bio = 6;</code>
   */
  java.lang.String getBio();
  /**
   * <code>string bio = 6;</code>
   */
  com.google.protobuf.ByteString
      getBioBytes();

  /**
   * <code>string avatar_url = 7;</code>
   */
  java.lang.String getAvatarUrl();
  /**
   * <code>string avatar_url = 7;</code>
   */
  com.google.protobuf.ByteString
      getAvatarUrlBytes();

  /**
   * <code>string headline = 8;</code>
   */
  java.lang.String getHeadline();
  /**
   * <code>string headline = 8;</code>
   */
  com.google.protobuf.ByteString
      getHeadlineBytes();

  /**
   * <code>string currentPosition = 9;</code>
   */
  java.lang.String getCurrentPosition();
  /**
   * <code>string currentPosition = 9;</code>
   */
  com.google.protobuf.ByteString
      getCurrentPositionBytes();

  /**
   * <code>.employed.io.Industry industry = 10;</code>
   */
  int getIndustryValue();
  /**
   * <code>.employed.io.Industry industry = 10;</code>
   */
  io.employed.proto.Industry getIndustry();

  /**
   * <code>.employed.io.Location location = 11;</code>
   */
  boolean hasLocation();
  /**
   * <code>.employed.io.Location location = 11;</code>
   */
  io.employed.proto.Location getLocation();
  /**
   * <code>.employed.io.Location location = 11;</code>
   */
  io.employed.proto.LocationOrBuilder getLocationOrBuilder();

  /**
   * <code>repeated string skills = 12;</code>
   */
  java.util.List<java.lang.String>
      getSkillsList();
  /**
   * <code>repeated string skills = 12;</code>
   */
  int getSkillsCount();
  /**
   * <code>repeated string skills = 12;</code>
   */
  java.lang.String getSkills(int index);
  /**
   * <code>repeated string skills = 12;</code>
   */
  com.google.protobuf.ByteString
      getSkillsBytes(int index);

  /**
   * <code>repeated string tags = 13;</code>
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 13;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 13;</code>
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 13;</code>
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);
}
