// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/job-seeker/job_seeker_request.proto

package io.employed.proto;

public interface JobSeekersByTagsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.JobSeekersByTagsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string tags = 1;</code>
   */
  java.util.List<String>
      getTagsList();
  /**
   * <code>repeated string tags = 1;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 1;</code>
   */
  String getTags(int index);
  /**
   * <code>repeated string tags = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);
}
