// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/job-seeker/job_seeker_request.proto

package io.employed.proto;

public final class JobSeekerRequestProto {
  private JobSeekerRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_JobSeekersByTagsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_JobSeekersByTagsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_JobSeekersByTagsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_JobSeekersByTagsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_JobSeekersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_JobSeekersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,protocol/job-seeker/job_seeker_request" +
      ".proto\022\013employed.io\032$protocol/job-seeker" +
      "/job_seeker.proto\"\'\n\027JobSeekersByTagsReq" +
      "uest\022\014\n\004tags\030\001 \003(\t\"G\n\030JobSeekersByTagsRe" +
      "sponse\022+\n\013job_seekers\030\001 \003(\0132\026.employed.i" +
      "o.JobSeeker\"A\n\022JobSeekersResponse\022+\n\013job" +
      "_seekers\030\001 \003(\0132\026.employed.io.JobSeekerB," +
      "\n\021io.employed.protoB\025JobSeekerRequestPro" +
      "toP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.employed.proto.JobSeekerProto.getDescriptor(),
        }, assigner);
    internal_static_employed_io_JobSeekersByTagsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employed_io_JobSeekersByTagsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_JobSeekersByTagsRequest_descriptor,
        new java.lang.String[] { "Tags", });
    internal_static_employed_io_JobSeekersByTagsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_employed_io_JobSeekersByTagsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_JobSeekersByTagsResponse_descriptor,
        new java.lang.String[] { "JobSeekers", });
    internal_static_employed_io_JobSeekersResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_employed_io_JobSeekersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_JobSeekersResponse_descriptor,
        new java.lang.String[] { "JobSeekers", });
    io.employed.proto.JobSeekerProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
