// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/job-seeker/job_seeker_request.proto

package io.employed.proto;

/**
 * Protobuf type {@code employed.io.JobSeekersByTagsResponse}
 */
public  final class JobSeekersByTagsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employed.io.JobSeekersByTagsResponse)
    JobSeekersByTagsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobSeekersByTagsResponse.newBuilder() to construct.
  private JobSeekersByTagsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobSeekersByTagsResponse() {
    jobSeekers_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobSeekersByTagsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              jobSeekers_ = new java.util.ArrayList<JobSeeker>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobSeekers_.add(
                input.readMessage(JobSeeker.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        jobSeekers_ = java.util.Collections.unmodifiableList(jobSeekers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return JobSeekerRequestProto.internal_static_employed_io_JobSeekersByTagsResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return JobSeekerRequestProto.internal_static_employed_io_JobSeekersByTagsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            JobSeekersByTagsResponse.class, Builder.class);
  }

  public static final int JOB_SEEKERS_FIELD_NUMBER = 1;
  private java.util.List<JobSeeker> jobSeekers_;
  /**
   * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
   */
  public java.util.List<JobSeeker> getJobSeekersList() {
    return jobSeekers_;
  }
  /**
   * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
   */
  public java.util.List<? extends JobSeekerOrBuilder>
      getJobSeekersOrBuilderList() {
    return jobSeekers_;
  }
  /**
   * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
   */
  public int getJobSeekersCount() {
    return jobSeekers_.size();
  }
  /**
   * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
   */
  public JobSeeker getJobSeekers(int index) {
    return jobSeekers_.get(index);
  }
  /**
   * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
   */
  public JobSeekerOrBuilder getJobSeekersOrBuilder(
      int index) {
    return jobSeekers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobSeekers_.size(); i++) {
      output.writeMessage(1, jobSeekers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobSeekers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobSeekers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof JobSeekersByTagsResponse)) {
      return super.equals(obj);
    }
    JobSeekersByTagsResponse other = (JobSeekersByTagsResponse) obj;

    boolean result = true;
    result = result && getJobSeekersList()
        .equals(other.getJobSeekersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobSeekersCount() > 0) {
      hash = (37 * hash) + JOB_SEEKERS_FIELD_NUMBER;
      hash = (53 * hash) + getJobSeekersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static JobSeekersByTagsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobSeekersByTagsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobSeekersByTagsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobSeekersByTagsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobSeekersByTagsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobSeekersByTagsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobSeekersByTagsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JobSeekersByTagsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static JobSeekersByTagsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static JobSeekersByTagsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static JobSeekersByTagsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JobSeekersByTagsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(JobSeekersByTagsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employed.io.JobSeekersByTagsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employed.io.JobSeekersByTagsResponse)
      io.employed.proto.JobSeekersByTagsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JobSeekerRequestProto.internal_static_employed_io_JobSeekersByTagsResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JobSeekerRequestProto.internal_static_employed_io_JobSeekersByTagsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JobSeekersByTagsResponse.class, Builder.class);
    }

    // Construct using io.employed.proto.JobSeekersByTagsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobSeekersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (jobSeekersBuilder_ == null) {
        jobSeekers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobSeekersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return JobSeekerRequestProto.internal_static_employed_io_JobSeekersByTagsResponse_descriptor;
    }

    public JobSeekersByTagsResponse getDefaultInstanceForType() {
      return JobSeekersByTagsResponse.getDefaultInstance();
    }

    public JobSeekersByTagsResponse build() {
      JobSeekersByTagsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public JobSeekersByTagsResponse buildPartial() {
      JobSeekersByTagsResponse result = new JobSeekersByTagsResponse(this);
      int from_bitField0_ = bitField0_;
      if (jobSeekersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          jobSeekers_ = java.util.Collections.unmodifiableList(jobSeekers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobSeekers_ = jobSeekers_;
      } else {
        result.jobSeekers_ = jobSeekersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof JobSeekersByTagsResponse) {
        return mergeFrom((JobSeekersByTagsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(JobSeekersByTagsResponse other) {
      if (other == JobSeekersByTagsResponse.getDefaultInstance()) return this;
      if (jobSeekersBuilder_ == null) {
        if (!other.jobSeekers_.isEmpty()) {
          if (jobSeekers_.isEmpty()) {
            jobSeekers_ = other.jobSeekers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobSeekersIsMutable();
            jobSeekers_.addAll(other.jobSeekers_);
          }
          onChanged();
        }
      } else {
        if (!other.jobSeekers_.isEmpty()) {
          if (jobSeekersBuilder_.isEmpty()) {
            jobSeekersBuilder_.dispose();
            jobSeekersBuilder_ = null;
            jobSeekers_ = other.jobSeekers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobSeekersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobSeekersFieldBuilder() : null;
          } else {
            jobSeekersBuilder_.addAllMessages(other.jobSeekers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      JobSeekersByTagsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (JobSeekersByTagsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<JobSeeker> jobSeekers_ =
      java.util.Collections.emptyList();
    private void ensureJobSeekersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        jobSeekers_ = new java.util.ArrayList<JobSeeker>(jobSeekers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        JobSeeker, JobSeeker.Builder, JobSeekerOrBuilder> jobSeekersBuilder_;

    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public java.util.List<JobSeeker> getJobSeekersList() {
      if (jobSeekersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobSeekers_);
      } else {
        return jobSeekersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public int getJobSeekersCount() {
      if (jobSeekersBuilder_ == null) {
        return jobSeekers_.size();
      } else {
        return jobSeekersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public JobSeeker getJobSeekers(int index) {
      if (jobSeekersBuilder_ == null) {
        return jobSeekers_.get(index);
      } else {
        return jobSeekersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder setJobSeekers(
        int index, JobSeeker value) {
      if (jobSeekersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobSeekersIsMutable();
        jobSeekers_.set(index, value);
        onChanged();
      } else {
        jobSeekersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder setJobSeekers(
        int index, JobSeeker.Builder builderForValue) {
      if (jobSeekersBuilder_ == null) {
        ensureJobSeekersIsMutable();
        jobSeekers_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobSeekersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder addJobSeekers(JobSeeker value) {
      if (jobSeekersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobSeekersIsMutable();
        jobSeekers_.add(value);
        onChanged();
      } else {
        jobSeekersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder addJobSeekers(
        int index, JobSeeker value) {
      if (jobSeekersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobSeekersIsMutable();
        jobSeekers_.add(index, value);
        onChanged();
      } else {
        jobSeekersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder addJobSeekers(
        JobSeeker.Builder builderForValue) {
      if (jobSeekersBuilder_ == null) {
        ensureJobSeekersIsMutable();
        jobSeekers_.add(builderForValue.build());
        onChanged();
      } else {
        jobSeekersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder addJobSeekers(
        int index, JobSeeker.Builder builderForValue) {
      if (jobSeekersBuilder_ == null) {
        ensureJobSeekersIsMutable();
        jobSeekers_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobSeekersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder addAllJobSeekers(
        Iterable<? extends JobSeeker> values) {
      if (jobSeekersBuilder_ == null) {
        ensureJobSeekersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobSeekers_);
        onChanged();
      } else {
        jobSeekersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder clearJobSeekers() {
      if (jobSeekersBuilder_ == null) {
        jobSeekers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobSeekersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public Builder removeJobSeekers(int index) {
      if (jobSeekersBuilder_ == null) {
        ensureJobSeekersIsMutable();
        jobSeekers_.remove(index);
        onChanged();
      } else {
        jobSeekersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public JobSeeker.Builder getJobSeekersBuilder(
        int index) {
      return getJobSeekersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public JobSeekerOrBuilder getJobSeekersOrBuilder(
        int index) {
      if (jobSeekersBuilder_ == null) {
        return jobSeekers_.get(index);  } else {
        return jobSeekersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public java.util.List<? extends JobSeekerOrBuilder>
         getJobSeekersOrBuilderList() {
      if (jobSeekersBuilder_ != null) {
        return jobSeekersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobSeekers_);
      }
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public JobSeeker.Builder addJobSeekersBuilder() {
      return getJobSeekersFieldBuilder().addBuilder(
          JobSeeker.getDefaultInstance());
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public JobSeeker.Builder addJobSeekersBuilder(
        int index) {
      return getJobSeekersFieldBuilder().addBuilder(
          index, JobSeeker.getDefaultInstance());
    }
    /**
     * <code>repeated .employed.io.JobSeeker job_seekers = 1;</code>
     */
    public java.util.List<JobSeeker.Builder>
         getJobSeekersBuilderList() {
      return getJobSeekersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        JobSeeker, JobSeeker.Builder, JobSeekerOrBuilder>
        getJobSeekersFieldBuilder() {
      if (jobSeekersBuilder_ == null) {
        jobSeekersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            JobSeeker, JobSeeker.Builder, JobSeekerOrBuilder>(
                jobSeekers_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        jobSeekers_ = null;
      }
      return jobSeekersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employed.io.JobSeekersByTagsResponse)
  }

  // @@protoc_insertion_point(class_scope:employed.io.JobSeekersByTagsResponse)
  private static final JobSeekersByTagsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new JobSeekersByTagsResponse();
  }

  public static JobSeekersByTagsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobSeekersByTagsResponse>
      PARSER = new com.google.protobuf.AbstractParser<JobSeekersByTagsResponse>() {
    public JobSeekersByTagsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new JobSeekersByTagsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobSeekersByTagsResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<JobSeekersByTagsResponse> getParserForType() {
    return PARSER;
  }

  public JobSeekersByTagsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

