// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/login/login_request.proto

package io.employed.proto;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.employed.io.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.employed.io.Status status = 1;</code>
   */
  io.employed.proto.Status getStatus();

  /**
   * <code>.employed.io.User user = 2;</code>
   */
  boolean hasUser();
  /**
   * <code>.employed.io.User user = 2;</code>
   */
  io.employed.proto.User getUser();
  /**
   * <code>.employed.io.User user = 2;</code>
   */
  io.employed.proto.UserOrBuilder getUserOrBuilder();
}
