// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/match/match.proto

package io.employed.proto;

public final class MatchProto {
  private MatchProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_Match_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_Match_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032protocol/match/match.proto\022\013employed.i" +
      "o\"<\n\005Match\022\020\n\010match_id\030\001 \001(\t\022\022\n\nchannel_" +
      "id\030\002 \001(\t\022\r\n\005users\030\003 \003(\tB!\n\021io.employed.p" +
      "rotoB\nMatchProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_employed_io_Match_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employed_io_Match_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_Match_descriptor,
        new String[] { "MatchId", "ChannelId", "Users", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
