// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/match/match_request.proto

package io.employed.proto;

/**
 * Protobuf type {@code employed.io.MatchesByUserIdsResponse}
 */
public  final class MatchesByUserIdsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employed.io.MatchesByUserIdsResponse)
    MatchesByUserIdsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MatchesByUserIdsResponse.newBuilder() to construct.
  private MatchesByUserIdsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MatchesByUserIdsResponse() {
    matches_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MatchesByUserIdsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              matches_ = new java.util.ArrayList<Match>();
              mutable_bitField0_ |= 0x00000001;
            }
            matches_.add(
                input.readMessage(Match.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        matches_ = java.util.Collections.unmodifiableList(matches_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MatchRequestProto.internal_static_employed_io_MatchesByUserIdsResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MatchRequestProto.internal_static_employed_io_MatchesByUserIdsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MatchesByUserIdsResponse.class, Builder.class);
  }

  public static final int MATCHES_FIELD_NUMBER = 1;
  private java.util.List<Match> matches_;
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  public java.util.List<Match> getMatchesList() {
    return matches_;
  }
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  public java.util.List<? extends MatchOrBuilder>
      getMatchesOrBuilderList() {
    return matches_;
  }
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  public int getMatchesCount() {
    return matches_.size();
  }
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  public Match getMatches(int index) {
    return matches_.get(index);
  }
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  public MatchOrBuilder getMatchesOrBuilder(
      int index) {
    return matches_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < matches_.size(); i++) {
      output.writeMessage(1, matches_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < matches_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, matches_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MatchesByUserIdsResponse)) {
      return super.equals(obj);
    }
    MatchesByUserIdsResponse other = (MatchesByUserIdsResponse) obj;

    boolean result = true;
    result = result && getMatchesList()
        .equals(other.getMatchesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMatchesCount() > 0) {
      hash = (37 * hash) + MATCHES_FIELD_NUMBER;
      hash = (53 * hash) + getMatchesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MatchesByUserIdsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MatchesByUserIdsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MatchesByUserIdsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MatchesByUserIdsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MatchesByUserIdsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MatchesByUserIdsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MatchesByUserIdsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MatchesByUserIdsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MatchesByUserIdsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MatchesByUserIdsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MatchesByUserIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MatchesByUserIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MatchesByUserIdsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employed.io.MatchesByUserIdsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employed.io.MatchesByUserIdsResponse)
      io.employed.proto.MatchesByUserIdsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MatchRequestProto.internal_static_employed_io_MatchesByUserIdsResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MatchRequestProto.internal_static_employed_io_MatchesByUserIdsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MatchesByUserIdsResponse.class, Builder.class);
    }

    // Construct using io.employed.proto.MatchesByUserIdsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMatchesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (matchesBuilder_ == null) {
        matches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        matchesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MatchRequestProto.internal_static_employed_io_MatchesByUserIdsResponse_descriptor;
    }

    public MatchesByUserIdsResponse getDefaultInstanceForType() {
      return MatchesByUserIdsResponse.getDefaultInstance();
    }

    public MatchesByUserIdsResponse build() {
      MatchesByUserIdsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public MatchesByUserIdsResponse buildPartial() {
      MatchesByUserIdsResponse result = new MatchesByUserIdsResponse(this);
      int from_bitField0_ = bitField0_;
      if (matchesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          matches_ = java.util.Collections.unmodifiableList(matches_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.matches_ = matches_;
      } else {
        result.matches_ = matchesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MatchesByUserIdsResponse) {
        return mergeFrom((MatchesByUserIdsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MatchesByUserIdsResponse other) {
      if (other == MatchesByUserIdsResponse.getDefaultInstance()) return this;
      if (matchesBuilder_ == null) {
        if (!other.matches_.isEmpty()) {
          if (matches_.isEmpty()) {
            matches_ = other.matches_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatchesIsMutable();
            matches_.addAll(other.matches_);
          }
          onChanged();
        }
      } else {
        if (!other.matches_.isEmpty()) {
          if (matchesBuilder_.isEmpty()) {
            matchesBuilder_.dispose();
            matchesBuilder_ = null;
            matches_ = other.matches_;
            bitField0_ = (bitField0_ & ~0x00000001);
            matchesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMatchesFieldBuilder() : null;
          } else {
            matchesBuilder_.addAllMessages(other.matches_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MatchesByUserIdsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MatchesByUserIdsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Match> matches_ =
      java.util.Collections.emptyList();
    private void ensureMatchesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        matches_ = new java.util.ArrayList<Match>(matches_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Match, Match.Builder, MatchOrBuilder> matchesBuilder_;

    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public java.util.List<Match> getMatchesList() {
      if (matchesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(matches_);
      } else {
        return matchesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public int getMatchesCount() {
      if (matchesBuilder_ == null) {
        return matches_.size();
      } else {
        return matchesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Match getMatches(int index) {
      if (matchesBuilder_ == null) {
        return matches_.get(index);
      } else {
        return matchesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder setMatches(
        int index, Match value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.set(index, value);
        onChanged();
      } else {
        matchesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder setMatches(
        int index, Match.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.set(index, builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder addMatches(Match value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.add(value);
        onChanged();
      } else {
        matchesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder addMatches(
        int index, Match value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.add(index, value);
        onChanged();
      } else {
        matchesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder addMatches(
        Match.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.add(builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder addMatches(
        int index, Match.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.add(index, builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder addAllMatches(
        Iterable<? extends Match> values) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, matches_);
        onChanged();
      } else {
        matchesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder clearMatches() {
      if (matchesBuilder_ == null) {
        matches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        matchesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Builder removeMatches(int index) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.remove(index);
        onChanged();
      } else {
        matchesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Match.Builder getMatchesBuilder(
        int index) {
      return getMatchesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public MatchOrBuilder getMatchesOrBuilder(
        int index) {
      if (matchesBuilder_ == null) {
        return matches_.get(index);  } else {
        return matchesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public java.util.List<? extends MatchOrBuilder>
         getMatchesOrBuilderList() {
      if (matchesBuilder_ != null) {
        return matchesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(matches_);
      }
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Match.Builder addMatchesBuilder() {
      return getMatchesFieldBuilder().addBuilder(
          Match.getDefaultInstance());
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public Match.Builder addMatchesBuilder(
        int index) {
      return getMatchesFieldBuilder().addBuilder(
          index, Match.getDefaultInstance());
    }
    /**
     * <code>repeated .employed.io.Match matches = 1;</code>
     */
    public java.util.List<Match.Builder>
         getMatchesBuilderList() {
      return getMatchesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Match, Match.Builder, MatchOrBuilder>
        getMatchesFieldBuilder() {
      if (matchesBuilder_ == null) {
        matchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Match, Match.Builder, MatchOrBuilder>(
                matches_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        matches_ = null;
      }
      return matchesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employed.io.MatchesByUserIdsResponse)
  }

  // @@protoc_insertion_point(class_scope:employed.io.MatchesByUserIdsResponse)
  private static final MatchesByUserIdsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MatchesByUserIdsResponse();
  }

  public static MatchesByUserIdsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatchesByUserIdsResponse>
      PARSER = new com.google.protobuf.AbstractParser<MatchesByUserIdsResponse>() {
    public MatchesByUserIdsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatchesByUserIdsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MatchesByUserIdsResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MatchesByUserIdsResponse> getParserForType() {
    return PARSER;
  }

  public MatchesByUserIdsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

