// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/match/match_request.proto

package io.employed.proto;

/**
 * Protobuf type {@code employed.io.MatchesResponse}
 */
public  final class MatchesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employed.io.MatchesResponse)
    MatchesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MatchesResponse.newBuilder() to construct.
  private MatchesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MatchesResponse() {
    match_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MatchesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              match_ = new java.util.ArrayList<io.employed.proto.Match>();
              mutable_bitField0_ |= 0x00000001;
            }
            match_.add(
                input.readMessage(io.employed.proto.Match.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        match_ = java.util.Collections.unmodifiableList(match_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.employed.proto.MatchRequestProto.internal_static_employed_io_MatchesResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.employed.proto.MatchRequestProto.internal_static_employed_io_MatchesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.employed.proto.MatchesResponse.class, io.employed.proto.MatchesResponse.Builder.class);
  }

  public static final int MATCH_FIELD_NUMBER = 1;
  private java.util.List<io.employed.proto.Match> match_;
  /**
   * <code>repeated .employed.io.Match match = 1;</code>
   */
  public java.util.List<io.employed.proto.Match> getMatchList() {
    return match_;
  }
  /**
   * <code>repeated .employed.io.Match match = 1;</code>
   */
  public java.util.List<? extends io.employed.proto.MatchOrBuilder> 
      getMatchOrBuilderList() {
    return match_;
  }
  /**
   * <code>repeated .employed.io.Match match = 1;</code>
   */
  public int getMatchCount() {
    return match_.size();
  }
  /**
   * <code>repeated .employed.io.Match match = 1;</code>
   */
  public io.employed.proto.Match getMatch(int index) {
    return match_.get(index);
  }
  /**
   * <code>repeated .employed.io.Match match = 1;</code>
   */
  public io.employed.proto.MatchOrBuilder getMatchOrBuilder(
      int index) {
    return match_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < match_.size(); i++) {
      output.writeMessage(1, match_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < match_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, match_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.employed.proto.MatchesResponse)) {
      return super.equals(obj);
    }
    io.employed.proto.MatchesResponse other = (io.employed.proto.MatchesResponse) obj;

    boolean result = true;
    result = result && getMatchList()
        .equals(other.getMatchList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMatchCount() > 0) {
      hash = (37 * hash) + MATCH_FIELD_NUMBER;
      hash = (53 * hash) + getMatchList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.employed.proto.MatchesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.MatchesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.MatchesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.MatchesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.MatchesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.MatchesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.MatchesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.employed.proto.MatchesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.employed.proto.MatchesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.employed.proto.MatchesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.employed.proto.MatchesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.employed.proto.MatchesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.employed.proto.MatchesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employed.io.MatchesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employed.io.MatchesResponse)
      io.employed.proto.MatchesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.employed.proto.MatchRequestProto.internal_static_employed_io_MatchesResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.employed.proto.MatchRequestProto.internal_static_employed_io_MatchesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.employed.proto.MatchesResponse.class, io.employed.proto.MatchesResponse.Builder.class);
    }

    // Construct using io.employed.proto.MatchesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMatchFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (matchBuilder_ == null) {
        match_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        matchBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.employed.proto.MatchRequestProto.internal_static_employed_io_MatchesResponse_descriptor;
    }

    public io.employed.proto.MatchesResponse getDefaultInstanceForType() {
      return io.employed.proto.MatchesResponse.getDefaultInstance();
    }

    public io.employed.proto.MatchesResponse build() {
      io.employed.proto.MatchesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.employed.proto.MatchesResponse buildPartial() {
      io.employed.proto.MatchesResponse result = new io.employed.proto.MatchesResponse(this);
      int from_bitField0_ = bitField0_;
      if (matchBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          match_ = java.util.Collections.unmodifiableList(match_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.match_ = match_;
      } else {
        result.match_ = matchBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.employed.proto.MatchesResponse) {
        return mergeFrom((io.employed.proto.MatchesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.employed.proto.MatchesResponse other) {
      if (other == io.employed.proto.MatchesResponse.getDefaultInstance()) return this;
      if (matchBuilder_ == null) {
        if (!other.match_.isEmpty()) {
          if (match_.isEmpty()) {
            match_ = other.match_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatchIsMutable();
            match_.addAll(other.match_);
          }
          onChanged();
        }
      } else {
        if (!other.match_.isEmpty()) {
          if (matchBuilder_.isEmpty()) {
            matchBuilder_.dispose();
            matchBuilder_ = null;
            match_ = other.match_;
            bitField0_ = (bitField0_ & ~0x00000001);
            matchBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMatchFieldBuilder() : null;
          } else {
            matchBuilder_.addAllMessages(other.match_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.employed.proto.MatchesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.employed.proto.MatchesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.employed.proto.Match> match_ =
      java.util.Collections.emptyList();
    private void ensureMatchIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        match_ = new java.util.ArrayList<io.employed.proto.Match>(match_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.employed.proto.Match, io.employed.proto.Match.Builder, io.employed.proto.MatchOrBuilder> matchBuilder_;

    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public java.util.List<io.employed.proto.Match> getMatchList() {
      if (matchBuilder_ == null) {
        return java.util.Collections.unmodifiableList(match_);
      } else {
        return matchBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public int getMatchCount() {
      if (matchBuilder_ == null) {
        return match_.size();
      } else {
        return matchBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public io.employed.proto.Match getMatch(int index) {
      if (matchBuilder_ == null) {
        return match_.get(index);
      } else {
        return matchBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder setMatch(
        int index, io.employed.proto.Match value) {
      if (matchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchIsMutable();
        match_.set(index, value);
        onChanged();
      } else {
        matchBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder setMatch(
        int index, io.employed.proto.Match.Builder builderForValue) {
      if (matchBuilder_ == null) {
        ensureMatchIsMutable();
        match_.set(index, builderForValue.build());
        onChanged();
      } else {
        matchBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder addMatch(io.employed.proto.Match value) {
      if (matchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchIsMutable();
        match_.add(value);
        onChanged();
      } else {
        matchBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder addMatch(
        int index, io.employed.proto.Match value) {
      if (matchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchIsMutable();
        match_.add(index, value);
        onChanged();
      } else {
        matchBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder addMatch(
        io.employed.proto.Match.Builder builderForValue) {
      if (matchBuilder_ == null) {
        ensureMatchIsMutable();
        match_.add(builderForValue.build());
        onChanged();
      } else {
        matchBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder addMatch(
        int index, io.employed.proto.Match.Builder builderForValue) {
      if (matchBuilder_ == null) {
        ensureMatchIsMutable();
        match_.add(index, builderForValue.build());
        onChanged();
      } else {
        matchBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder addAllMatch(
        java.lang.Iterable<? extends io.employed.proto.Match> values) {
      if (matchBuilder_ == null) {
        ensureMatchIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, match_);
        onChanged();
      } else {
        matchBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder clearMatch() {
      if (matchBuilder_ == null) {
        match_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        matchBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public Builder removeMatch(int index) {
      if (matchBuilder_ == null) {
        ensureMatchIsMutable();
        match_.remove(index);
        onChanged();
      } else {
        matchBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public io.employed.proto.Match.Builder getMatchBuilder(
        int index) {
      return getMatchFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public io.employed.proto.MatchOrBuilder getMatchOrBuilder(
        int index) {
      if (matchBuilder_ == null) {
        return match_.get(index);  } else {
        return matchBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public java.util.List<? extends io.employed.proto.MatchOrBuilder> 
         getMatchOrBuilderList() {
      if (matchBuilder_ != null) {
        return matchBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(match_);
      }
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public io.employed.proto.Match.Builder addMatchBuilder() {
      return getMatchFieldBuilder().addBuilder(
          io.employed.proto.Match.getDefaultInstance());
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public io.employed.proto.Match.Builder addMatchBuilder(
        int index) {
      return getMatchFieldBuilder().addBuilder(
          index, io.employed.proto.Match.getDefaultInstance());
    }
    /**
     * <code>repeated .employed.io.Match match = 1;</code>
     */
    public java.util.List<io.employed.proto.Match.Builder> 
         getMatchBuilderList() {
      return getMatchFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.employed.proto.Match, io.employed.proto.Match.Builder, io.employed.proto.MatchOrBuilder> 
        getMatchFieldBuilder() {
      if (matchBuilder_ == null) {
        matchBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.employed.proto.Match, io.employed.proto.Match.Builder, io.employed.proto.MatchOrBuilder>(
                match_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        match_ = null;
      }
      return matchBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employed.io.MatchesResponse)
  }

  // @@protoc_insertion_point(class_scope:employed.io.MatchesResponse)
  private static final io.employed.proto.MatchesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.employed.proto.MatchesResponse();
  }

  public static io.employed.proto.MatchesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatchesResponse>
      PARSER = new com.google.protobuf.AbstractParser<MatchesResponse>() {
    public MatchesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatchesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MatchesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatchesResponse> getParserForType() {
    return PARSER;
  }

  public io.employed.proto.MatchesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

