// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/match/match_request.proto

package io.employed.proto;

public interface MatchesByUserIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.MatchesByUserIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  java.util.List<Match>
      getMatchesList();
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  Match getMatches(int index);
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  int getMatchesCount();
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  java.util.List<? extends MatchOrBuilder>
      getMatchesOrBuilderList();
  /**
   * <code>repeated .employed.io.Match matches = 1;</code>
   */
  MatchOrBuilder getMatchesOrBuilder(
          int index);
}
