// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/employed_io_service.proto

package io.employed.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageId = 1;</code>
   */
  String getMessageId();
  /**
   * <code>string messageId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string timeZone = 2;</code>
   */
  String getTimeZone();
  /**
   * <code>string timeZone = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeZoneBytes();

  /**
   * <code>string text = 3;</code>
   */
  String getText();
  /**
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
