// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/recruiter/recruiter_request.proto

package io.employed.proto;

/**
 * Protobuf type {@code employed.io.RecruitersResponse}
 */
public  final class RecruitersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employed.io.RecruitersResponse)
    RecruitersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecruitersResponse.newBuilder() to construct.
  private RecruitersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecruitersResponse() {
    recruiters_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecruitersResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              recruiters_ = new java.util.ArrayList<Recruiter>();
              mutable_bitField0_ |= 0x00000001;
            }
            recruiters_.add(
                input.readMessage(Recruiter.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        recruiters_ = java.util.Collections.unmodifiableList(recruiters_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RecruiterRequestProto.internal_static_employed_io_RecruitersResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RecruiterRequestProto.internal_static_employed_io_RecruitersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RecruitersResponse.class, Builder.class);
  }

  public static final int RECRUITERS_FIELD_NUMBER = 1;
  private java.util.List<Recruiter> recruiters_;
  /**
   * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
   */
  public java.util.List<Recruiter> getRecruitersList() {
    return recruiters_;
  }
  /**
   * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
   */
  public java.util.List<? extends RecruiterOrBuilder>
      getRecruitersOrBuilderList() {
    return recruiters_;
  }
  /**
   * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
   */
  public int getRecruitersCount() {
    return recruiters_.size();
  }
  /**
   * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
   */
  public Recruiter getRecruiters(int index) {
    return recruiters_.get(index);
  }
  /**
   * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
   */
  public RecruiterOrBuilder getRecruitersOrBuilder(
      int index) {
    return recruiters_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recruiters_.size(); i++) {
      output.writeMessage(1, recruiters_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < recruiters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, recruiters_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RecruitersResponse)) {
      return super.equals(obj);
    }
    RecruitersResponse other = (RecruitersResponse) obj;

    boolean result = true;
    result = result && getRecruitersList()
        .equals(other.getRecruitersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecruitersCount() > 0) {
      hash = (37 * hash) + RECRUITERS_FIELD_NUMBER;
      hash = (53 * hash) + getRecruitersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RecruitersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RecruitersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RecruitersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RecruitersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RecruitersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RecruitersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RecruitersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RecruitersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RecruitersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RecruitersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RecruitersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RecruitersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RecruitersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employed.io.RecruitersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employed.io.RecruitersResponse)
      io.employed.proto.RecruitersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecruiterRequestProto.internal_static_employed_io_RecruitersResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecruiterRequestProto.internal_static_employed_io_RecruitersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecruitersResponse.class, Builder.class);
    }

    // Construct using io.employed.proto.RecruitersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecruitersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (recruitersBuilder_ == null) {
        recruiters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        recruitersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RecruiterRequestProto.internal_static_employed_io_RecruitersResponse_descriptor;
    }

    public RecruitersResponse getDefaultInstanceForType() {
      return RecruitersResponse.getDefaultInstance();
    }

    public RecruitersResponse build() {
      RecruitersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public RecruitersResponse buildPartial() {
      RecruitersResponse result = new RecruitersResponse(this);
      int from_bitField0_ = bitField0_;
      if (recruitersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          recruiters_ = java.util.Collections.unmodifiableList(recruiters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recruiters_ = recruiters_;
      } else {
        result.recruiters_ = recruitersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RecruitersResponse) {
        return mergeFrom((RecruitersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RecruitersResponse other) {
      if (other == RecruitersResponse.getDefaultInstance()) return this;
      if (recruitersBuilder_ == null) {
        if (!other.recruiters_.isEmpty()) {
          if (recruiters_.isEmpty()) {
            recruiters_ = other.recruiters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecruitersIsMutable();
            recruiters_.addAll(other.recruiters_);
          }
          onChanged();
        }
      } else {
        if (!other.recruiters_.isEmpty()) {
          if (recruitersBuilder_.isEmpty()) {
            recruitersBuilder_.dispose();
            recruitersBuilder_ = null;
            recruiters_ = other.recruiters_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recruitersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecruitersFieldBuilder() : null;
          } else {
            recruitersBuilder_.addAllMessages(other.recruiters_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RecruitersResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RecruitersResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Recruiter> recruiters_ =
      java.util.Collections.emptyList();
    private void ensureRecruitersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        recruiters_ = new java.util.ArrayList<Recruiter>(recruiters_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Recruiter, Recruiter.Builder, RecruiterOrBuilder> recruitersBuilder_;

    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public java.util.List<Recruiter> getRecruitersList() {
      if (recruitersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recruiters_);
      } else {
        return recruitersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public int getRecruitersCount() {
      if (recruitersBuilder_ == null) {
        return recruiters_.size();
      } else {
        return recruitersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Recruiter getRecruiters(int index) {
      if (recruitersBuilder_ == null) {
        return recruiters_.get(index);
      } else {
        return recruitersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder setRecruiters(
        int index, Recruiter value) {
      if (recruitersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecruitersIsMutable();
        recruiters_.set(index, value);
        onChanged();
      } else {
        recruitersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder setRecruiters(
        int index, Recruiter.Builder builderForValue) {
      if (recruitersBuilder_ == null) {
        ensureRecruitersIsMutable();
        recruiters_.set(index, builderForValue.build());
        onChanged();
      } else {
        recruitersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder addRecruiters(Recruiter value) {
      if (recruitersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecruitersIsMutable();
        recruiters_.add(value);
        onChanged();
      } else {
        recruitersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder addRecruiters(
        int index, Recruiter value) {
      if (recruitersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecruitersIsMutable();
        recruiters_.add(index, value);
        onChanged();
      } else {
        recruitersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder addRecruiters(
        Recruiter.Builder builderForValue) {
      if (recruitersBuilder_ == null) {
        ensureRecruitersIsMutable();
        recruiters_.add(builderForValue.build());
        onChanged();
      } else {
        recruitersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder addRecruiters(
        int index, Recruiter.Builder builderForValue) {
      if (recruitersBuilder_ == null) {
        ensureRecruitersIsMutable();
        recruiters_.add(index, builderForValue.build());
        onChanged();
      } else {
        recruitersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder addAllRecruiters(
        Iterable<? extends Recruiter> values) {
      if (recruitersBuilder_ == null) {
        ensureRecruitersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recruiters_);
        onChanged();
      } else {
        recruitersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder clearRecruiters() {
      if (recruitersBuilder_ == null) {
        recruiters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recruitersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Builder removeRecruiters(int index) {
      if (recruitersBuilder_ == null) {
        ensureRecruitersIsMutable();
        recruiters_.remove(index);
        onChanged();
      } else {
        recruitersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Recruiter.Builder getRecruitersBuilder(
        int index) {
      return getRecruitersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public RecruiterOrBuilder getRecruitersOrBuilder(
        int index) {
      if (recruitersBuilder_ == null) {
        return recruiters_.get(index);  } else {
        return recruitersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public java.util.List<? extends RecruiterOrBuilder>
         getRecruitersOrBuilderList() {
      if (recruitersBuilder_ != null) {
        return recruitersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recruiters_);
      }
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Recruiter.Builder addRecruitersBuilder() {
      return getRecruitersFieldBuilder().addBuilder(
          Recruiter.getDefaultInstance());
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public Recruiter.Builder addRecruitersBuilder(
        int index) {
      return getRecruitersFieldBuilder().addBuilder(
          index, Recruiter.getDefaultInstance());
    }
    /**
     * <code>repeated .employed.io.Recruiter recruiters = 1;</code>
     */
    public java.util.List<Recruiter.Builder>
         getRecruitersBuilderList() {
      return getRecruitersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Recruiter, Recruiter.Builder, RecruiterOrBuilder>
        getRecruitersFieldBuilder() {
      if (recruitersBuilder_ == null) {
        recruitersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Recruiter, Recruiter.Builder, RecruiterOrBuilder>(
                recruiters_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        recruiters_ = null;
      }
      return recruitersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employed.io.RecruitersResponse)
  }

  // @@protoc_insertion_point(class_scope:employed.io.RecruitersResponse)
  private static final RecruitersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RecruitersResponse();
  }

  public static RecruitersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecruitersResponse>
      PARSER = new com.google.protobuf.AbstractParser<RecruitersResponse>() {
    public RecruitersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecruitersResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecruitersResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RecruitersResponse> getParserForType() {
    return PARSER;
  }

  public RecruitersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

