// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/employed_io_service.proto

package io.employed.proto;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.Status)
    com.google.protobuf.MessageOrBuilder {
}
