// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/user/user.proto

package io.employed.proto;

/**
 * Protobuf type {@code employed.io.User}
 */
public  final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:employed.io.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    userId_ = "";
    role_ = 0;
    handle_ = "";
    login_ = "";
    password_ = "";
    matches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    pendingMatches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    rejectedMatches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            role_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            handle_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            login_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              matches_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000020;
            }
            matches_.add(s);
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              pendingMatches_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000040;
            }
            pendingMatches_.add(s);
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              rejectedMatches_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000080;
            }
            rejectedMatches_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        matches_ = matches_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        pendingMatches_ = pendingMatches_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        rejectedMatches_ = rejectedMatches_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.employed.proto.UserProto.internal_static_employed_io_User_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.employed.proto.UserProto.internal_static_employed_io_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.employed.proto.User.class, io.employed.proto.User.Builder.class);
  }

  /**
   * Protobuf enum {@code employed.io.User.Role}
   */
  public enum Role
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JOB_SEEKER = 0;</code>
     */
    JOB_SEEKER(0),
    /**
     * <code>RECRUITER = 1;</code>
     */
    RECRUITER(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>JOB_SEEKER = 0;</code>
     */
    public static final int JOB_SEEKER_VALUE = 0;
    /**
     * <code>RECRUITER = 1;</code>
     */
    public static final int RECRUITER_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Role valueOf(int value) {
      return forNumber(value);
    }

    public static Role forNumber(int value) {
      switch (value) {
        case 0: return JOB_SEEKER;
        case 1: return RECRUITER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Role>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Role> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Role>() {
            public Role findValueByNumber(int number) {
              return Role.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.employed.proto.User.getDescriptor().getEnumTypes().get(0);
    }

    private static final Role[] VALUES = values();

    public static Role valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Role(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:employed.io.User.Role)
  }

  private int bitField0_;
  public static final int USER_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userId_;
  /**
   * <code>string user_id = 1;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLE_FIELD_NUMBER = 2;
  private int role_;
  /**
   * <code>.employed.io.User.Role role = 2;</code>
   */
  public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.employed.io.User.Role role = 2;</code>
   */
  public io.employed.proto.User.Role getRole() {
    io.employed.proto.User.Role result = io.employed.proto.User.Role.valueOf(role_);
    return result == null ? io.employed.proto.User.Role.UNRECOGNIZED : result;
  }

  public static final int HANDLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object handle_;
  /**
   * <code>string handle = 3;</code>
   */
  public java.lang.String getHandle() {
    java.lang.Object ref = handle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      handle_ = s;
      return s;
    }
  }
  /**
   * <code>string handle = 3;</code>
   */
  public com.google.protobuf.ByteString
      getHandleBytes() {
    java.lang.Object ref = handle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      handle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGIN_FIELD_NUMBER = 4;
  private volatile java.lang.Object login_;
  /**
   * <code>string login = 4;</code>
   */
  public java.lang.String getLogin() {
    java.lang.Object ref = login_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      login_ = s;
      return s;
    }
  }
  /**
   * <code>string login = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLoginBytes() {
    java.lang.Object ref = login_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      login_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 5;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 5;</code>
   */
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATCHES_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList matches_;
  /**
   * <code>repeated string matches = 6;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getMatchesList() {
    return matches_;
  }
  /**
   * <code>repeated string matches = 6;</code>
   */
  public int getMatchesCount() {
    return matches_.size();
  }
  /**
   * <code>repeated string matches = 6;</code>
   */
  public java.lang.String getMatches(int index) {
    return matches_.get(index);
  }
  /**
   * <code>repeated string matches = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMatchesBytes(int index) {
    return matches_.getByteString(index);
  }

  public static final int PENDING_MATCHES_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList pendingMatches_;
  /**
   * <code>repeated string pending_matches = 7;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getPendingMatchesList() {
    return pendingMatches_;
  }
  /**
   * <code>repeated string pending_matches = 7;</code>
   */
  public int getPendingMatchesCount() {
    return pendingMatches_.size();
  }
  /**
   * <code>repeated string pending_matches = 7;</code>
   */
  public java.lang.String getPendingMatches(int index) {
    return pendingMatches_.get(index);
  }
  /**
   * <code>repeated string pending_matches = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPendingMatchesBytes(int index) {
    return pendingMatches_.getByteString(index);
  }

  public static final int REJECTED_MATCHES_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList rejectedMatches_;
  /**
   * <code>repeated string rejected_matches = 8;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getRejectedMatchesList() {
    return rejectedMatches_;
  }
  /**
   * <code>repeated string rejected_matches = 8;</code>
   */
  public int getRejectedMatchesCount() {
    return rejectedMatches_.size();
  }
  /**
   * <code>repeated string rejected_matches = 8;</code>
   */
  public java.lang.String getRejectedMatches(int index) {
    return rejectedMatches_.get(index);
  }
  /**
   * <code>repeated string rejected_matches = 8;</code>
   */
  public com.google.protobuf.ByteString
      getRejectedMatchesBytes(int index) {
    return rejectedMatches_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (role_ != io.employed.proto.User.Role.JOB_SEEKER.getNumber()) {
      output.writeEnum(2, role_);
    }
    if (!getHandleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, handle_);
    }
    if (!getLoginBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, login_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, password_);
    }
    for (int i = 0; i < matches_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, matches_.getRaw(i));
    }
    for (int i = 0; i < pendingMatches_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pendingMatches_.getRaw(i));
    }
    for (int i = 0; i < rejectedMatches_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, rejectedMatches_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (role_ != io.employed.proto.User.Role.JOB_SEEKER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, role_);
    }
    if (!getHandleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, handle_);
    }
    if (!getLoginBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, login_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, password_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < matches_.size(); i++) {
        dataSize += computeStringSizeNoTag(matches_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMatchesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < pendingMatches_.size(); i++) {
        dataSize += computeStringSizeNoTag(pendingMatches_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPendingMatchesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < rejectedMatches_.size(); i++) {
        dataSize += computeStringSizeNoTag(rejectedMatches_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRejectedMatchesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.employed.proto.User)) {
      return super.equals(obj);
    }
    io.employed.proto.User other = (io.employed.proto.User) obj;

    boolean result = true;
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && role_ == other.role_;
    result = result && getHandle()
        .equals(other.getHandle());
    result = result && getLogin()
        .equals(other.getLogin());
    result = result && getPassword()
        .equals(other.getPassword());
    result = result && getMatchesList()
        .equals(other.getMatchesList());
    result = result && getPendingMatchesList()
        .equals(other.getPendingMatchesList());
    result = result && getRejectedMatchesList()
        .equals(other.getRejectedMatchesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + role_;
    hash = (37 * hash) + HANDLE_FIELD_NUMBER;
    hash = (53 * hash) + getHandle().hashCode();
    hash = (37 * hash) + LOGIN_FIELD_NUMBER;
    hash = (53 * hash) + getLogin().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    if (getMatchesCount() > 0) {
      hash = (37 * hash) + MATCHES_FIELD_NUMBER;
      hash = (53 * hash) + getMatchesList().hashCode();
    }
    if (getPendingMatchesCount() > 0) {
      hash = (37 * hash) + PENDING_MATCHES_FIELD_NUMBER;
      hash = (53 * hash) + getPendingMatchesList().hashCode();
    }
    if (getRejectedMatchesCount() > 0) {
      hash = (37 * hash) + REJECTED_MATCHES_FIELD_NUMBER;
      hash = (53 * hash) + getRejectedMatchesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.employed.proto.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.employed.proto.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.employed.proto.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.employed.proto.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.employed.proto.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.employed.proto.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.employed.proto.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.employed.proto.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.employed.proto.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code employed.io.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:employed.io.User)
      io.employed.proto.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.employed.proto.UserProto.internal_static_employed_io_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.employed.proto.UserProto.internal_static_employed_io_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.employed.proto.User.class, io.employed.proto.User.Builder.class);
    }

    // Construct using io.employed.proto.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      userId_ = "";

      role_ = 0;

      handle_ = "";

      login_ = "";

      password_ = "";

      matches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      pendingMatches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      rejectedMatches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.employed.proto.UserProto.internal_static_employed_io_User_descriptor;
    }

    public io.employed.proto.User getDefaultInstanceForType() {
      return io.employed.proto.User.getDefaultInstance();
    }

    public io.employed.proto.User build() {
      io.employed.proto.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.employed.proto.User buildPartial() {
      io.employed.proto.User result = new io.employed.proto.User(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.userId_ = userId_;
      result.role_ = role_;
      result.handle_ = handle_;
      result.login_ = login_;
      result.password_ = password_;
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        matches_ = matches_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.matches_ = matches_;
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        pendingMatches_ = pendingMatches_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.pendingMatches_ = pendingMatches_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        rejectedMatches_ = rejectedMatches_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.rejectedMatches_ = rejectedMatches_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.employed.proto.User) {
        return mergeFrom((io.employed.proto.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.employed.proto.User other) {
      if (other == io.employed.proto.User.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (other.role_ != 0) {
        setRoleValue(other.getRoleValue());
      }
      if (!other.getHandle().isEmpty()) {
        handle_ = other.handle_;
        onChanged();
      }
      if (!other.getLogin().isEmpty()) {
        login_ = other.login_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.matches_.isEmpty()) {
        if (matches_.isEmpty()) {
          matches_ = other.matches_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureMatchesIsMutable();
          matches_.addAll(other.matches_);
        }
        onChanged();
      }
      if (!other.pendingMatches_.isEmpty()) {
        if (pendingMatches_.isEmpty()) {
          pendingMatches_ = other.pendingMatches_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensurePendingMatchesIsMutable();
          pendingMatches_.addAll(other.pendingMatches_);
        }
        onChanged();
      }
      if (!other.rejectedMatches_.isEmpty()) {
        if (rejectedMatches_.isEmpty()) {
          rejectedMatches_ = other.rejectedMatches_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureRejectedMatchesIsMutable();
          rejectedMatches_.addAll(other.rejectedMatches_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.employed.proto.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.employed.proto.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private int role_ = 0;
    /**
     * <code>.employed.io.User.Role role = 2;</code>
     */
    public int getRoleValue() {
      return role_;
    }
    /**
     * <code>.employed.io.User.Role role = 2;</code>
     */
    public Builder setRoleValue(int value) {
      role_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.employed.io.User.Role role = 2;</code>
     */
    public io.employed.proto.User.Role getRole() {
      io.employed.proto.User.Role result = io.employed.proto.User.Role.valueOf(role_);
      return result == null ? io.employed.proto.User.Role.UNRECOGNIZED : result;
    }
    /**
     * <code>.employed.io.User.Role role = 2;</code>
     */
    public Builder setRole(io.employed.proto.User.Role value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      role_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.employed.io.User.Role role = 2;</code>
     */
    public Builder clearRole() {
      
      role_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object handle_ = "";
    /**
     * <code>string handle = 3;</code>
     */
    public java.lang.String getHandle() {
      java.lang.Object ref = handle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        handle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string handle = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHandleBytes() {
      java.lang.Object ref = handle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        handle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string handle = 3;</code>
     */
    public Builder setHandle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      handle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string handle = 3;</code>
     */
    public Builder clearHandle() {
      
      handle_ = getDefaultInstance().getHandle();
      onChanged();
      return this;
    }
    /**
     * <code>string handle = 3;</code>
     */
    public Builder setHandleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      handle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object login_ = "";
    /**
     * <code>string login = 4;</code>
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        login_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string login = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string login = 4;</code>
     */
    public Builder setLogin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      login_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string login = 4;</code>
     */
    public Builder clearLogin() {
      
      login_ = getDefaultInstance().getLogin();
      onChanged();
      return this;
    }
    /**
     * <code>string login = 4;</code>
     */
    public Builder setLoginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      login_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 5;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 5;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 5;</code>
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 5;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList matches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMatchesIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        matches_ = new com.google.protobuf.LazyStringArrayList(matches_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMatchesList() {
      return matches_.getUnmodifiableView();
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public int getMatchesCount() {
      return matches_.size();
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public java.lang.String getMatches(int index) {
      return matches_.get(index);
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMatchesBytes(int index) {
      return matches_.getByteString(index);
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public Builder setMatches(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMatchesIsMutable();
      matches_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public Builder addMatches(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMatchesIsMutable();
      matches_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public Builder addAllMatches(
        java.lang.Iterable<java.lang.String> values) {
      ensureMatchesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, matches_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public Builder clearMatches() {
      matches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matches = 6;</code>
     */
    public Builder addMatchesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMatchesIsMutable();
      matches_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList pendingMatches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePendingMatchesIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        pendingMatches_ = new com.google.protobuf.LazyStringArrayList(pendingMatches_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPendingMatchesList() {
      return pendingMatches_.getUnmodifiableView();
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public int getPendingMatchesCount() {
      return pendingMatches_.size();
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public java.lang.String getPendingMatches(int index) {
      return pendingMatches_.get(index);
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPendingMatchesBytes(int index) {
      return pendingMatches_.getByteString(index);
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public Builder setPendingMatches(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePendingMatchesIsMutable();
      pendingMatches_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public Builder addPendingMatches(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePendingMatchesIsMutable();
      pendingMatches_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public Builder addAllPendingMatches(
        java.lang.Iterable<java.lang.String> values) {
      ensurePendingMatchesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, pendingMatches_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public Builder clearPendingMatches() {
      pendingMatches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string pending_matches = 7;</code>
     */
    public Builder addPendingMatchesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePendingMatchesIsMutable();
      pendingMatches_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList rejectedMatches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRejectedMatchesIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        rejectedMatches_ = new com.google.protobuf.LazyStringArrayList(rejectedMatches_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRejectedMatchesList() {
      return rejectedMatches_.getUnmodifiableView();
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public int getRejectedMatchesCount() {
      return rejectedMatches_.size();
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public java.lang.String getRejectedMatches(int index) {
      return rejectedMatches_.get(index);
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRejectedMatchesBytes(int index) {
      return rejectedMatches_.getByteString(index);
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public Builder setRejectedMatches(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRejectedMatchesIsMutable();
      rejectedMatches_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public Builder addRejectedMatches(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRejectedMatchesIsMutable();
      rejectedMatches_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public Builder addAllRejectedMatches(
        java.lang.Iterable<java.lang.String> values) {
      ensureRejectedMatchesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, rejectedMatches_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public Builder clearRejectedMatches() {
      rejectedMatches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string rejected_matches = 8;</code>
     */
    public Builder addRejectedMatchesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRejectedMatchesIsMutable();
      rejectedMatches_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:employed.io.User)
  }

  // @@protoc_insertion_point(class_scope:employed.io.User)
  private static final io.employed.proto.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.employed.proto.User();
  }

  public static io.employed.proto.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  public io.employed.proto.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

