// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/user.proto

package io.employed.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string handle = 3;</code>
   */
  String getHandle();
  /**
   * <code>string handle = 3;</code>
   */
  com.google.protobuf.ByteString
      getHandleBytes();

  /**
   * <code>string first_name = 4;</code>
   */
  String getFirstName();
  /**
   * <code>string first_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 5;</code>
   */
  String getLastName();
  /**
   * <code>string last_name = 5;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string bio = 6;</code>
   */
  String getBio();
  /**
   * <code>string bio = 6;</code>
   */
  com.google.protobuf.ByteString
      getBioBytes();

  /**
   * <code>string email = 7;</code>
   */
  String getEmail();
  /**
   * <code>string email = 7;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phone_number = 8;</code>
   */
  String getPhoneNumber();
  /**
   * <code>string phone_number = 8;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
