// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/user/user.proto

package io.employed.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_employed_io_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_employed_io_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030protocol/user/user.proto\022\013employed.io\"" +
      "\331\001\n\004User\022\017\n\007user_id\030\001 \001(\t\022$\n\004role\030\002 \001(\0162" +
      "\026.employed.io.User.Role\022\016\n\006handle\030\003 \001(\t\022" +
      "\r\n\005login\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\022\017\n\007matc" +
      "hes\030\006 \003(\t\022\027\n\017pending_matches\030\007 \003(\t\022\030\n\020re" +
      "jected_matches\030\010 \003(\t\"%\n\004Role\022\016\n\nJOB_SEEK" +
      "ER\020\000\022\r\n\tRECRUITER\020\001B \n\021io.employed.proto" +
      "B\tUserProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_employed_io_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_employed_io_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_employed_io_User_descriptor,
        new String[] { "UserId", "Role", "Handle", "Login", "Password", "Matches", "PendingMatches", "RejectedMatches", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
