// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/user/user_request.proto

package io.employed.proto;

public interface UsersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:employed.io.UsersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .employed.io.User users = 1;</code>
   */
  java.util.List<io.employed.proto.User> 
      getUsersList();
  /**
   * <code>repeated .employed.io.User users = 1;</code>
   */
  io.employed.proto.User getUsers(int index);
  /**
   * <code>repeated .employed.io.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .employed.io.User users = 1;</code>
   */
  java.util.List<? extends io.employed.proto.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .employed.io.User users = 1;</code>
   */
  io.employed.proto.UserOrBuilder getUsersOrBuilder(
      int index);
}
